#!/bin/sh
 
# Host to connect
VC_HOST=localhost
# Port as defined with ser2net
VC_PORT=3002
 
if [ "$1" = "autoconf" ]; then
	echo yes;
	exit 0;
fi

if [ "$1" = "config" ]; then
cat << __EOM
graph_title heating temperatures
graph_args --lower-limit -20 --upper-limit 100
graph_category Viessmann
graph_vlabel Temp C
graph_scale no
graph_info This graph shows some of the temps
getOutsideTemp.label Outside Temp
getOutsideTemp.info Outside temperature in degrees C.
getWaterTemp.label Hot Water
getWaterTemp.info hot water temperature in degrees C
getBoilerTemp.label Boiler Temp
getBoilerTemp.info boiler temperature in degrees C.
getExhaustTemp.label Exhaust
getExhaustTemp.info Exhaust temperature in degrees C.
#getExhaustTemp.warning 90
#getExhaustTemp.critical 120
#getTemp17A.label Return water 17A
#getTemp17A.info 17A water temperature
getTemp17B.label Return water 17B
getTemp17B.info 17B water temperature
getHotWaterTemp1.label Hot Water Temperature 1
getHotWaterTemp1.info HotWater Temperature Sensor 1
getHotWaterTemp2.label Hot Water Temperature 2
getHotWaterTemp2.info HotWater Temperature Sensor 2
getRoomTempSP.label Room Temperature Setpoint
getRoomTempSP.info Room Temperature Setpoint
getDHWTempSP.label Hot Water Temperature Setpoint
getDHWTempSP.info Hot Water Temperature Setpoint
__EOM
exit 0;
fi
 
/usr/local/bin/vclient -m --host $VC_HOST --port $VC_PORT getTemp17A getOutsideTemp getWaterTemp getBoilerTemp getExhaustTemp getTemp17B getHotWaterTemp1 getHotWaterTemp2 getRoomTempSP getDHWTempSP

	
exit 0
